with open('rust-app/backend/src/handlers/ws.rs', 'r') as f:
    content = f.read()

# Fix clippy warning for identical if-else blocks
content = content.replace('                                                            if room_id != &my_loc {\n                                                                false\n                                                            } else if let Some(target) = &message.recipient_id {\n                                                                *target == my_id_clone || message.user_id == my_id_clone\n                                                            } else if message.user_id == my_id_clone {\n                                                                true // Echo to self\n                                                            } else {\n                                                                true\n                                                            }', '                                                            if room_id != &my_loc {\n                                                                false\n                                                            } else if let Some(target) = &message.recipient_id {\n                                                                *target == my_id_clone || message.user_id == my_id_clone\n                                                            } else {\n                                                                true\n                                                            }')

content = content.replace('                                                    if room_id != &my_loc {\n                                                        false\n                                                    } else if let Some(target) = &message.recipient_id {\n                                                        *target == my_id_clone || message.user_id == my_id_clone\n                                                    } else if message.user_id == my_id_clone {\n                                                        true // Echo to self\n                                                    } else {\n                                                        true\n                                                    }', '                                                    if room_id != &my_loc {\n                                                        false\n                                                    } else if let Some(target) = &message.recipient_id {\n                                                        *target == my_id_clone || message.user_id == my_id_clone\n                                                    } else {\n                                                        true\n                                                    }')


with open('rust-app/backend/src/handlers/ws.rs', 'w') as f:
    f.write(content)
